CREATE TABLE "DP_ORGANIZATION" (
	"ORG_ID" VARCHAR(256) NOT NULL,
	"ORG_NAME" VARCHAR(256) NOT NULL,
	"BUSINESS_OWNER" VARCHAR(256) NOT NULL,
	"BUSINESS_OWNER_CONTACT" VARCHAR(256) NOT NULL,
	"BUSINESS_OWNER_EMAIL" VARCHAR(256) NOT NULL,
	UNIQUE ("ORG_NAME"),
	PRIMARY KEY("ORG_ID")
);

CREATE TABLE "DP_ORGANIZATION_ASSETS" (
	"ASSERT_ID" VARCHAR(256) NOT NULL,
	"FILE_NAME" VARCHAR(256) NOT NULL,
	"FILE_CONTENT" BYTEA NOT NULL,
	"FILE_TYPE" VARCHAR(256) NOT NULL,
	"FILE_PATH" VARCHAR(1000) NOT NULL,
	"ORG_ID" VARCHAR(256) NOT NULL,
	FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
	UNIQUE ("FILE_NAME", "FILE_TYPE", "FILE_PATH", "ORG_ID"),
	PRIMARY KEY("ASSERT_ID")
);