apiVersion: devportal.api-platform.wso2.com/v1
kind: RestApi

metadata:
  name: echo-api-v1.0

spec:
  type: REST
  displayName: Echo API
  version: v1.0
  description: Sample echo API. Requires API key authentication.
  provider: WSO2
  status: PUBLISHED
  gatewayType: wso2/api-platform
  referenceID: echo-api-v1.0

  tags:
    - echo
    - api-key

  labels:
    - default

  subscriptionPolicies: []

  visibility: PUBLIC
  visibleGroups: []

  businessInformation:
    businessOwner: Platform Owner
    businessOwnerEmail: support@example.com
    technicalOwner: API Team
    technicalOwnerEmail: architecture@example.com

  endpoints:
    sandboxUrl: http://localhost:8080/echo
    productionUrl: http://localhost:8080/echo
