const APIMetadata = {
    REFERENCE_ID: 'REFERENCE_ID',
    API_NAME: 'API_NAME',
    API_DESCRIPTION: 'API_DESCRIPTION',
    API_VERSION: 'API_VERSION',
    API_TYPE: 'API_TYPE',
    VISIBILITY: 'VISIBILITY',
    VISIBLE_GROUPS: 'VISIBLE_GROUPS',
    TECHNICAL_OWNER: 'TECHNICAL_OWNER',
    TECHNICAL_OWNER_EMAIL: 'TECHNICAL_OWNER_EMAIL',
    BUSINESS_OWNER: 'BUSINESS_OWNER',
    BUSINESS_OWNER_EMAIL: 'BUSINESS_OWNER_EMAIL',
    SANDBOX_URL: 'SANDBOX_URL',
    PRODUCTION_URL: 'PRODUCTION_URL',
    METADATA_SEARCH: 'METADATA_SEARCH'
}

const API_ID = 'API_ID';
const ORG_ID = 'ORG_ID';

const APIContent = {
    
}