name: "✍️ Create a Task"
description: Create a new task.
labels: ["Type/Task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Select affected component.
      options:
        - Analytics
        - APICTL
        - APIM
        - IntegrationStudio
        - MI
        - MIDashboard
        - SI
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter component version.
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Related Issues
      description: Mention if any related issues.
    validations:
      required: false
  - type: input
    id: suggested
    attributes:
      label: Suggested Labels
      description: Mention if any suggested labels.
    validations:
      required: false