#!/usr/bin/env node
/*
 * Seeds sample API workflows into an organization's default view.
 *
 *   node artifacts/api_flow_data.js [orgHandle] [viewName] [--prune]
 *
 * Defaults to `ashera100 default`. --prune also deletes workflows in that view which this
 * manifest does not define; without it, existing ones are left untouched. BASE_URL=... in
 * the environment overrides the spec URLs baked into the Arazzo sourceDescriptions, for
 * seeding a deployment other than the one config.json points at.
 *
 * It writes to whichever database config.json currently names - check with
 * `node use-db.js status` in the local-db tooling before running it.
 *
 * A companion to api_data.sh / org_data.sh / theme_data.sh, in Node rather than bash
 * because the agent prompt each workflow carries is generated by the application:
 * apiFlowService.generateAgentPrompt is what the create wizard calls, and hand-writing
 * that text into SQL would drift from it the first time the template changes.
 *
 * The workflows below target the three APIs a fresh test org tends to have - the REST
 * Reading List API, countries-graphql and chat-service - and between them cover every
 * state the settings list renders: both content types, PUBLISHED and DRAFT, PUBLIC and
 * PRIVATE, agent-visible and hidden. The Arazzo steps use that API's real operationIds
 * and real request schemas, so the workflow detail page and the source-description
 * check in the wizard both resolve instead of showing a broken reference.
 *
 * Re-running replaces the samples it owns (matched on handle) and leaves anything else
 * in the org alone, so it is safe after a dump restore.
 */
const path = require('path');

// src/db/sequelize and apiFlowService both read config.json via process.cwd().
const REPO_ROOT = path.resolve(__dirname, '..');
if (process.cwd() !== REPO_ROOT) process.chdir(REPO_ROOT);

const sequelize = require('../src/db/sequelize');
const adminDao = require('../src/dao/admin');
const apiMetadataDao = require('../src/dao/apiMetadata');
const apiFlowDao = require('../src/dao/apiFlow');
const { generateAgentPrompt } = require('../src/services/apiFlowService');
const config = require('../config.json');

const args = process.argv.slice(2).filter((a) => !a.startsWith('--'));
const flags = new Set(process.argv.slice(2).filter((a) => a.startsWith('--')));

const ORG_HANDLE = args[0] || 'ashera100';
const VIEW_NAME = args[1] || 'default';
/* Spec URLs are absolute and must name the deployment the workflows will be read on, so
   this follows the DB the repo is pointed at rather than being hardcoded. BASE_URL
   overrides it when seeding a deployment whose config.json is not the one in hand. */
const BASE_URL = process.env.BASE_URL || config.baseUrl || 'https://localhost:3000';
/* Deletes workflows in this org/view that this manifest does not define. Off by default:
   it removes other people's work, so it has to be asked for. */
const PRUNE = flags.has('--prune');

/** The URL the wizard writes into sourceDescriptions for an API in this org. */
const specUrl = (apiHandle) =>
    `${BASE_URL}/${ORG_HANDLE}/views/${VIEW_NAME}/api/${apiHandle}/docs/specification.json`;

const READING_LIST = 'reading-list-api-v1.0';
const LOCAL_GATEWAY = 'local-gateway-v1.0';
const COUNTRIES = 'countries-graphql-v1.0';
const CHAT = 'chat-service-v1.0';

/* ── Sample 1: Arazzo, the happy path across four operations ───────────────── */
const shelveAndStartReading = {
    arazzo: '1.0.0',
    info: {
        title: 'Shelve a Book and Start Reading',
        version: '1.0.0',
        description:
            'Adds a title to the reading list only if it is not already shelved, confirms it '
            + 'persisted, then moves it to "reading" so the caller ends up with one book in '
            + 'progress and its identifier.',
    },
    sourceDescriptions: [
        { name: 'readingList', url: specUrl(READING_LIST), type: 'openapi' },
    ],
    workflows: [{
        workflowId: 'shelveAndStartReading',
        summary: 'Shelve a book, verify it, and mark it as being read',
        description:
            'Guards against duplicates by listing the shelf first, creates the book, reads it '
            + 'back by id to confirm the write, and finishes by setting status to "reading".',
        inputs: {
            type: 'object',
            required: ['title', 'author'],
            properties: {
                title: { type: 'string', example: 'The Lord of the Rings' },
                author: { type: 'string', example: 'J. R. R. Tolkien' },
                start_immediately: {
                    type: 'boolean',
                    default: true,
                    description: 'When false the book is left at "to_read" instead of "reading".',
                },
            },
        },
        steps: [
            {
                stepId: 'listShelf',
                description: 'Read the whole shelf so the next step can tell a duplicate from a new title.',
                operationId: '$sourceDescriptions.readingList#listBooks',
                successCriteria: [{ condition: '$statusCode == 200' }],
                outputs: { shelf: '$response.body' },
                onSuccess: [{ name: 'shelfRead', type: 'goto', stepId: 'shelveBook' }],
                onFailure: [
                    {
                        name: 'shelfUnavailable',
                        type: 'retry',
                        retryAfter: 2,
                        retryLimit: 2,
                        criteria: [{ condition: '$statusCode >= 500' }],
                    },
                    {
                        name: 'shelfReadFailed',
                        type: 'end',
                        criteria: [{ condition: '$statusCode >= 400' }],
                        outputs: {
                            error_code: 'SHELF_READ_FAILED',
                            error_message: 'Could not read the reading list. Check the API subscription and token.',
                        },
                    },
                ],
            },
            {
                stepId: 'shelveBook',
                description:
                    'Create the book at "to_read". Skip this step and reuse the existing id if the '
                    + 'title already appears in $steps.listShelf.outputs.shelf.',
                operationId: '$sourceDescriptions.readingList#createBook',
                requestBody: {
                    contentType: 'application/json',
                    payload: {
                        title: '$inputs.title',
                        author: '$inputs.author',
                        status: 'to_read',
                    },
                },
                successCriteria: [{ condition: '$statusCode == 200 || $statusCode == 201' }],
                outputs: { book_id: '$response.body.id', book_status: '$response.body.status' },
                onSuccess: [{ name: 'bookShelved', type: 'goto', stepId: 'confirmShelved' }],
                onFailure: [{
                    name: 'shelveFailed',
                    type: 'end',
                    criteria: [{ condition: '$statusCode >= 400' }],
                    outputs: {
                        error_code: 'SHELVE_FAILED',
                        error_message: 'The book could not be added. Title and author are both required.',
                    },
                }],
            },
            {
                stepId: 'confirmShelved',
                description: 'Read the new book back by id, so a silent write failure surfaces here rather than later.',
                operationId: '$sourceDescriptions.readingList#getBookById',
                parameters: [{ name: 'id', in: 'path', value: '$steps.shelveBook.outputs.book_id' }],
                successCriteria: [
                    { condition: '$statusCode == 200' },
                    { condition: '$response.body.title == $inputs.title', context: '$response.body', type: 'jsonpath' },
                ],
                outputs: { confirmed_title: '$response.body.title', confirmed_author: '$response.body.author' },
                onSuccess: [{ name: 'confirmed', type: 'goto', stepId: 'startReading' }],
                onFailure: [{
                    name: 'notFoundAfterCreate',
                    type: 'end',
                    criteria: [{ condition: '$statusCode == 404' }],
                    outputs: {
                        error_code: 'BOOK_NOT_PERSISTED',
                        error_message: 'The book was accepted but cannot be read back. Retry the workflow.',
                    },
                }],
            },
            {
                stepId: 'startReading',
                description: 'Move the book to "reading". Status is the only field this API allows an update to.',
                operationId: '$sourceDescriptions.readingList#updateBookById',
                parameters: [{ name: 'id', in: 'path', value: '$steps.shelveBook.outputs.book_id' }],
                requestBody: {
                    contentType: 'application/json',
                    payload: { status: 'reading' },
                },
                successCriteria: [{ condition: '$statusCode == 200' }],
                outputs: { final_status: '$response.body.status' },
                onSuccess: [{ name: 'workflowComplete', type: 'end' }],
                onFailure: [{
                    name: 'statusUpdateFailed',
                    type: 'end',
                    criteria: [{ condition: '$statusCode >= 400' }],
                    outputs: {
                        warning_code: 'STATUS_UPDATE_FAILED',
                        warning_message: 'The book is shelved but still at "to_read".',
                    },
                }],
            },
        ],
        outputs: {
            book_id: '$steps.shelveBook.outputs.book_id',
            title: '$steps.confirmShelved.outputs.confirmed_title',
            author: '$steps.confirmShelved.outputs.confirmed_author',
            status: '$steps.startReading.outputs.final_status',
        },
    }],
};

/* ── Sample 2: Arazzo, a destructive path with an explicit guard ───────────── */
const retireFinishedBook = {
    arazzo: '1.0.0',
    info: {
        title: 'Retire a Finished Book',
        version: '1.0.0',
        description:
            'Finds a book by title, marks it read, and removes it from the shelf only after the '
            + 'caller confirms - the delete is irreversible and this API has no undo.',
    },
    sourceDescriptions: [
        { name: 'readingList', url: specUrl(READING_LIST), type: 'openapi' },
    ],
    workflows: [{
        workflowId: 'retireFinishedBook',
        summary: 'Mark a book read, then delete it once the caller confirms',
        description:
            'The shelf has no title filter, so the match is made over the full list. The delete '
            + 'step is deliberately gated on an input rather than run automatically.',
        inputs: {
            type: 'object',
            required: ['title'],
            properties: {
                title: { type: 'string', example: 'The Lord of the Rings' },
                confirm_delete: {
                    type: 'boolean',
                    default: false,
                    description: 'Must be explicitly true. Ask the user before setting it.',
                },
            },
        },
        steps: [
            {
                stepId: 'findBook',
                description: 'List the shelf and select the entry whose title matches $inputs.title.',
                operationId: '$sourceDescriptions.readingList#listBooks',
                successCriteria: [{ condition: '$statusCode == 200' }],
                outputs: { shelf: '$response.body' },
                onSuccess: [{ name: 'found', type: 'goto', stepId: 'markRead' }],
                onFailure: [{
                    name: 'shelfReadFailed',
                    type: 'end',
                    criteria: [{ condition: '$statusCode >= 400' }],
                    outputs: {
                        error_code: 'SHELF_READ_FAILED',
                        error_message: 'Could not read the reading list.',
                    },
                }],
            },
            {
                stepId: 'markRead',
                description: 'Set the matched book to "read" before it is retired, so history stays accurate.',
                operationId: '$sourceDescriptions.readingList#updateBookById',
                parameters: [{ name: 'id', in: 'path', value: '$steps.findBook.outputs.shelf[0].id' }],
                requestBody: {
                    contentType: 'application/json',
                    payload: { status: 'read' },
                },
                successCriteria: [{ condition: '$statusCode == 200' }],
                outputs: { book_id: '$response.body.id', book_status: '$response.body.status' },
                onSuccess: [{ name: 'marked', type: 'goto', stepId: 'retireBook' }],
                onFailure: [{
                    name: 'titleNotOnShelf',
                    type: 'end',
                    criteria: [{ condition: '$statusCode == 404' }],
                    outputs: {
                        error_code: 'TITLE_NOT_FOUND',
                        error_message: 'No book on the shelf matches that title.',
                    },
                }],
            },
            {
                stepId: 'retireBook',
                description:
                    'Delete the book. Run only when $inputs.confirm_delete is true; otherwise end here '
                    + 'and report the book as read but retained.',
                operationId: '$sourceDescriptions.readingList#deleteBookById',
                parameters: [{ name: 'id', in: 'path', value: '$steps.markRead.outputs.book_id' }],
                successCriteria: [{ condition: '$statusCode == 200 || $statusCode == 204' }],
                outputs: { retired: 'true' },
                onSuccess: [{ name: 'workflowComplete', type: 'end' }],
                onFailure: [{
                    name: 'deleteFailed',
                    type: 'end',
                    criteria: [{ condition: '$statusCode >= 400' }],
                    outputs: {
                        warning_code: 'DELETE_FAILED',
                        warning_message: 'The book is marked read but could not be removed.',
                    },
                }],
            },
        ],
        outputs: {
            book_id: '$steps.markRead.outputs.book_id',
            status: '$steps.markRead.outputs.book_status',
            retired: '$steps.retireBook.outputs.retired',
        },
    }],
};

/* ── Sample 3: Arazzo across two APIs, which is what Arazzo is actually for ─── */
const mirrorToLocalGateway = {
    arazzo: '1.0.0',
    info: {
        title: 'Mirror the Reading List to the Local Gateway',
        version: '1.0.0',
        description:
            'Copies every book the Reading List API holds onto the Local Gateway, skipping the '
            + 'ones already there, and reports what it added and what it left alone.',
    },
    sourceDescriptions: [
        { name: 'readingList', url: specUrl(READING_LIST), type: 'openapi' },
        { name: 'localGateway', url: specUrl(LOCAL_GATEWAY), type: 'openapi' },
    ],
    workflows: [{
        workflowId: 'mirrorReadingList',
        summary: 'Reconcile the Local Gateway shelf against the Reading List shelf',
        description:
            'Reads both shelves, then creates on the Local Gateway only the titles missing '
            + 'there. Idempotent by design: run it twice and the second run adds nothing, '
            + 'which is why the comparison happens before any write.',
        inputs: {
            type: 'object',
            properties: {
                dry_run: {
                    type: 'boolean',
                    default: false,
                    description: 'Report what would be copied without creating anything.',
                },
            },
        },
        steps: [
            {
                stepId: 'readSource',
                description: 'Read every book on the Reading List API - the shelf being mirrored from.',
                operationId: '$sourceDescriptions.readingList#listBooks',
                successCriteria: [{ condition: '$statusCode == 200' }],
                outputs: { source_books: '$response.body' },
                onSuccess: [{ name: 'sourceRead', type: 'goto', stepId: 'readTarget' }],
                onFailure: [
                    {
                        name: 'sourceRetry',
                        type: 'retry',
                        retryAfter: 2,
                        retryLimit: 2,
                        criteria: [{ condition: '$statusCode >= 500' }],
                    },
                    {
                        name: 'sourceUnavailable',
                        type: 'end',
                        criteria: [{ condition: '$statusCode >= 400' }],
                        outputs: {
                            error_code: 'SOURCE_UNAVAILABLE',
                            error_message: 'Could not read the Reading List API. Nothing was copied.',
                        },
                    },
                ],
            },
            {
                stepId: 'readTarget',
                description:
                    'Read the Local Gateway shelf. Both APIs proxy the same shape, so the titles '
                    + 'here are directly comparable with the ones from the previous step.',
                operationId: '$sourceDescriptions.localGateway#listBooks',
                successCriteria: [{ condition: '$statusCode == 200' }],
                outputs: { target_books: '$response.body' },
                onSuccess: [{ name: 'targetRead', type: 'goto', stepId: 'copyMissingBook' }],
                onFailure: [{
                    name: 'targetUnavailable',
                    type: 'end',
                    criteria: [{ condition: '$statusCode >= 400' }],
                    outputs: {
                        error_code: 'TARGET_UNAVAILABLE',
                        error_message: 'Could not read the Local Gateway. Nothing was copied.',
                    },
                }],
            },
            {
                stepId: 'copyMissingBook',
                description:
                    'For each title in $steps.readSource.outputs.source_books with no matching '
                    + 'title in $steps.readTarget.outputs.target_books, create it on the Local '
                    + 'Gateway carrying its status across. Skip entirely when $inputs.dry_run is '
                    + 'true, and report the would-be additions instead.',
                operationId: '$sourceDescriptions.localGateway#createBook',
                requestBody: {
                    contentType: 'application/json',
                    payload: {
                        title: '$steps.readSource.outputs.source_books[0].title',
                        author: '$steps.readSource.outputs.source_books[0].author',
                        status: '$steps.readSource.outputs.source_books[0].status',
                    },
                },
                successCriteria: [{ condition: '$statusCode == 200 || $statusCode == 201' }],
                outputs: { last_copied_id: '$response.body.id' },
                onSuccess: [{ name: 'mirrorComplete', type: 'end' }],
                onFailure: [{
                    name: 'copyFailed',
                    type: 'end',
                    criteria: [{ condition: '$statusCode >= 400' }],
                    outputs: {
                        error_code: 'COPY_FAILED',
                        error_message: 'A book could not be created on the Local Gateway. '
                            + 'The mirror is incomplete; re-run to retry only what is still missing.',
                    },
                }],
            },
        ],
        outputs: {
            source_books: '$steps.readSource.outputs.source_books',
            target_books: '$steps.readTarget.outputs.target_books',
            last_copied_id: '$steps.copyMissingBook.outputs.last_copied_id',
        },
    }],
};

/* ── Sample 4: Markdown, two protocols in one workflow ─────────────────────── */
const enrichWithCountryFacts = `# Enrich the Reading List with Author Country Facts

Adds context to a reading list by pairing each book's author with facts about the country
they are associated with. Spans two protocols on purpose: the reading list is REST, the
country data is GraphQL, and an agent has to switch style between them.

## APIs used

| API | Protocol | What it provides |
| --- | --- | --- |
| Reading List API (\`${READING_LIST}\`) | REST | The shelf: id, title, author, status |
| countries-graphql (\`countries-graphql-v1.0\`) | GraphQL | Country name, capital, currency, languages |

Read each API's specification from the portal before calling it, and collect whatever
credentials its security scheme requires from the user. Never guess a token.

## Steps

1. **Read the shelf.** \`GET /books\` on the Reading List API. Expect 200 and an array of
   books. If the array is empty, stop and tell the user there is nothing to enrich.

2. **Resolve each author to a country.** This is not in either API - infer it from your own
   knowledge of the author, and record your confidence. Where you are unsure, say so rather
   than inventing a country.

3. **Fetch country facts.** For each distinct country, query countries-graphql:

   \`\`\`graphql
   query CountryFacts($code: ID!) {
     country(code: $code) {
       name
       capital
       currency
       languages { name }
     }
   }
   \`\`\`

   Use the ISO 3166-1 alpha-2 code. If \`country\` comes back null, treat the code as wrong
   and skip that author rather than retrying.

4. **Produce the digest.** One row per book: title, author, status, country, capital,
   currency, primary language, and your confidence in the author-to-country mapping.

## Constraints

- Read-only. Do not create, update or delete anything on the reading list.
- Batch the GraphQL queries by distinct country - do not issue one request per book.
- If a step fails with a 4xx, stop; only retry on 5xx, at most three times.
`;

/* ── Sample 4: Markdown, draft and private, over a WebSocket API ───────────── */
const readingRoomChatDigest = `# Reading Room Chat Digest

Listens to the reading room chat for a fixed window and returns a digest of which books
were discussed. Draft: the summarisation rules below still need a second pass, and the
chat API has no history endpoint yet, so the window has to be observed live.

## API used

| API | Protocol | What it provides |
| --- | --- | --- |
| chat-service (\`chat-service-v1.0\`) | WebSocket | The live reading room message stream |

## Steps

1. **Open the socket.** Connect to chat-service using the URL and security scheme in its
   specification. If the handshake is rejected, report the status and stop - do not retry a
   rejected handshake in a loop.

2. **Observe for the requested window.** Default 15 minutes. Buffer messages in memory;
   keep sender, timestamp and text. Stop at the window's end or after 500 messages,
   whichever comes first.

3. **Extract book mentions.** A mention is a title in quotes, a title followed by an
   author, or an explicit "reading X". Ignore mentions inside quoted replies so a single
   message is not counted twice.

4. **Return the digest.** Per book: mention count, first and last mention time, and the
   two or three most representative lines. Then the overall message count and the number of
   distinct participants.

## Open questions before this leaves draft

- How should a book be matched against the reading list - exact title, or fuzzy?
- Should the digest write anything back, e.g. move a heavily-discussed book to "reading"?
- What is the right window default for a quiet room?

## Constraints

- Read-only, and no message content leaves the digest.
- Do not attribute quotes to named participants in the output; report counts, not identities.
`;

/* ── The manifest this script owns ───────────────────────────────────────────
   `requires` lists the API handles a workflow references. A workflow whose APIs the
   organization does not publish is skipped rather than seeded: a sourceDescriptions URL
   that 404s makes the workflow detail page show a broken reference and the wizard's
   source check fail, which is worse than the workflow being absent. Deployments differ -
   local has no Local Gateway, the hosted dev org does. */
const SAMPLES = [
    {
        name: 'Shelve a Book and Start Reading',
        handle: 'shelve-a-book-and-start-reading',
        description:
            'Adds a title to the reading list only if it is not already shelved, confirms it '
            + 'persisted, then moves it to "reading".',
        requires: [READING_LIST],
        contentType: 'ARAZZO',
        content: JSON.stringify(shelveAndStartReading),
        status: 'PUBLISHED',
        visibility: 'PUBLIC',
        agentVisibility: 'VISIBLE',
    },
    {
        name: 'Retire a Finished Book',
        handle: 'retire-a-finished-book',
        description:
            'Finds a book by title, marks it read, and removes it from the shelf only after the '
            + 'caller explicitly confirms the delete.',
        requires: [READING_LIST],
        contentType: 'ARAZZO',
        content: JSON.stringify(retireFinishedBook),
        status: 'PUBLISHED',
        visibility: 'PUBLIC',
        agentVisibility: 'VISIBLE',
    },
    {
        name: 'Mirror the Reading List to the Local Gateway',
        handle: 'mirror-the-reading-list-to-the-local-gateway',
        description:
            'Copies every book the Reading List API holds onto the Local Gateway, skipping the '
            + 'ones already there. Idempotent - a second run adds nothing.',
        requires: [READING_LIST, LOCAL_GATEWAY],
        contentType: 'ARAZZO',
        content: JSON.stringify(mirrorToLocalGateway),
        status: 'PUBLISHED',
        visibility: 'PUBLIC',
        agentVisibility: 'VISIBLE',
    },
    {
        name: 'Enrich the Reading List with Author Country Facts',
        handle: 'enrich-reading-list-with-country-facts',
        description:
            'Pairs every author on the reading list with facts about their country, crossing a '
            + 'REST API and a GraphQL API in one workflow.',
        requires: [READING_LIST, COUNTRIES],
        contentType: 'MD',
        content: enrichWithCountryFacts,
        status: 'PUBLISHED',
        visibility: 'PUBLIC',
        agentVisibility: 'VISIBLE',
    },
    {
        name: 'Reading Room Chat Digest',
        handle: 'reading-room-chat-digest',
        description:
            'Listens to the reading room WebSocket for a fixed window and digests which books '
            + 'were discussed. Still draft - the summarisation rules need a second pass.',
        requires: [CHAT],
        contentType: 'MD',
        content: readingRoomChatDigest,
        status: 'DRAFT',
        visibility: 'PRIVATE',
        agentVisibility: 'HIDDEN',
    },
];

async function main() {
    const orgID = await adminDao.getOrgId(ORG_HANDLE);
    if (!orgID) throw new Error(`organization not found: ${ORG_HANDLE}`);
    const viewId = await apiMetadataDao.getViewID(orgID, VIEW_NAME);
    if (!viewId) throw new Error(`view not found: ${ORG_HANDLE}/${VIEW_NAME}`);

    console.log(`org ${ORG_HANDLE} (${orgID})  view ${VIEW_NAME} (${viewId})`);
    console.log(`baseUrl ${BASE_URL}`);

    /* Which APIs this organization actually publishes, so a workflow is only seeded where
       every API it names can be resolved. */
    const publishedAPIs = await apiMetadataDao.getAPIMetadataByCondition({
        ORG_ID: orgID, STATUS: 'PUBLISHED',
    });
    const handles = new Set(publishedAPIs.map((a) => a.API_HANDLE));
    console.log(`published APIs: ${[...handles].sort().join(', ') || '(none)'}\n`);

    const applicable = [];
    for (const sample of SAMPLES) {
        const missing = (sample.requires || []).filter((h) => !handles.has(h));
        if (missing.length) {
            console.log(`  skipped   ${sample.handle}  (needs ${missing.join(', ')})`);
        } else {
            applicable.push(sample);
        }
    }

    if (PRUNE) {
        const keep = new Set(applicable.map((s) => s.handle));
        const existingAll = await apiFlowDao.getAllAPIFlows(orgID, viewId);
        for (const flow of existingAll) {
            if (keep.has(flow.HANDLE)) continue;
            const t = await sequelize.transaction();
            try {
                await apiFlowDao.deleteAPIFlow(orgID, viewId, flow.API_FLOW_ID, t);
                await t.commit();
                console.log(`  pruned    ${flow.HANDLE}  ("${flow.NAME}")`);
            } catch (error) {
                await t.rollback();
                throw error;
            }
        }
    }

    let created = 0;
    let replaced = 0;

    for (const sample of applicable) {
        const t = await sequelize.transaction();
        try {
            const existing = await apiFlowDao.getAPIFlowByHandle(orgID, viewId, sample.handle);
            if (existing) {
                await apiFlowDao.deleteAPIFlow(orgID, viewId, existing.API_FLOW_ID, t);
                replaced += 1;
            } else {
                created += 1;
            }

            await apiFlowDao.createAPIFlow(orgID, viewId, {
                name: sample.name,
                handle: sample.handle,
                description: sample.description,
                // Same call the create wizard makes, so these prompts match hand-made ones.
                agentPrompt: generateAgentPrompt(
                    sample.name, sample.description, [], ORG_HANDLE, VIEW_NAME, BASE_URL, sample.handle,
                ),
                status: sample.status,
                visibility: sample.visibility,
                agentVisibility: sample.agentVisibility,
                apiFlowDefinition: sample.content,
                contentType: sample.contentType,
            }, t);

            await t.commit();
            console.log(
                `  ${existing ? 'replaced' : 'created '}  ${sample.contentType.padEnd(8)}`
                + `${sample.status.padEnd(10)}${sample.handle}`,
            );
        } catch (error) {
            await t.rollback();
            console.error(`  FAILED    ${sample.handle}: ${error.message}`);
            throw error;
        }
    }

    console.log(`\n  ${created} created, ${replaced} replaced`);
    await sequelize.close();
}

main().catch((error) => {
    console.error(`\nerror: ${error.message}`);
    process.exit(1);
});
